### ISSUE TITLE
Package rhumsaa/uuid is abandoned, you should avoid using it. Use ramsey/uuid instead.

### ISSUE THREAD

**Issue by sc0rp10** [hautelook/sentry-client#7]

**Comment by ramsey** [comment]
Until hautelook/sentry-client updates their package to use ramsey/uuid, you may do the following in your project:

    composer require ramsey/uuid=^2.8

Since ramsey/uuid [indicates that it is a replacement for rhumsaa/uuid](https://github.com/ramsey/uuid/blob/36ebfcfc938e68f29345ea8931a788f8745f7663/composer.json#L53-L55), when Composer installs dependencies for hautelook/sentry-client, it will use ramsey/uuid instead, and all will be well, and you won't see the warning message again. :-)

**Comment by hjr3** [comment]
https://github.com/hautelook/sentry-client/pull/8

**Comment by hjr3** [comment]
Tagged new 1.0.0 release, so we should be good here. Closing issue.
